rules:
  unpinned-uses:
    config:
      policies:
        actions/*: ref-pin
        aws-actions/configure-aws-credentials: ref-pin
        astral-sh/setup-uv: ref-pin
        codecov/codecov-action: ref-pin
