# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  python: circleci/python@1.5.0
  codecov: codecov/codecov@3.1.0
  node: circleci/node@5.0.0

jobs:
  install_and_update_dependencies:
    docker:
      - image: cimg/python:3.8.12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
      - run: &install-pipenv pip install -U pipenv urllib3 pip --quiet --no-input
      - python/install-packages:
          pkg-manager: pipenv
          args: --dev
      - run: pipenv run pipenv check # before save_cache so an insecure cache is never saved
      - save_cache:
          when: on_success
          paths:
            - ~/.local/share/virtualenvs/
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

  run-tests:
    docker:
      - image: cimg/python:3.8.12
    working_directory: ~/repo/
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
      - run: *install-pipenv
      - run:
          name: Check formatting (ruff format)
          command: pipenv run ruff-format-check
      - run:
          name: Ruff
          command: pipenv run ruff-check
      - run:
          name: Run tests
          command: pipenv run pytest
      - codecov/upload:
          file: /home/circleci/project/coverage.xml
      - store_test_results:
          path: /home/circleci/project/test-results/

  deploy:
    working_directory: ~/repo/
    docker:
    - image: cimg/python:3.8.12-node
    parameters:
      dc-environment:
        type: enum
        enum: [ development, production ]
    steps:
    - checkout
    - attach_workspace:
        at: ~/repo/
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Pipfile.lock" }}
    - run: *install-pipenv
    - node/install-packages
    - run:
        name: CDK Synth
        command: cd dc_logging_aws && pipenv run npx aws-cdk synth
    - run:
        name: CDK Deploy
        command: cd dc_logging_aws && pipenv run npx aws-cdk deploy --require-approval=never

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - install_and_update_dependencies
      - run-tests:
          requires:
            - install_and_update_dependencies

      - deploy:
          name: cdk_deploy_development
          dc-environment: development
          requires:
            - run-tests
          context: [ deployment-development-monitoring ]
          filters: { branches: { only: [ main, master ] } }
      - deploy:
          name: cdk_deploy_production
          dc-environment: development
          requires:
            - run-tests
            - cdk_deploy_development
          context: [ deployment-production-monitoring ]
          filters: { branches: { only: [ main, master ] } }
